/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_mgs_rippleq1_LibNative */

#ifndef _Included_com_mgs_rippleq1_LibNative
#define _Included_com_mgs_rippleq1_LibNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mgs_rippleq1_LibNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mgs_rippleq1_LibNative_init
  (JNIEnv *, jclass);

/*
 * Class:     com_mgs_rippleq1_LibNative
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mgs_rippleq1_LibNative_resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mgs_rippleq1_LibNative
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mgs_rippleq1_LibNative_render
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
